version: '3.8'

services:
  app:
    build: .
    container_name: magic_card_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: magic_card_db
    environment:
      MYSQL_DATABASE: magic_card
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: magic_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
